### ISSUE TITLE
After the first messages read no more messages are received

### ISSUE THREAD

**Issue by a14n** [achilleasa/dart_amqp#1]
I just did a quick test with this package (version 0.0.1) and the following code. After the first message (or bunch of messages) no more messages are received and the rabbitmq queue grows up.

```dart
import "package:dart_amqp/dart_amqp.dart";

main() async {
  // auto-connect to localhost:5672 using guest credentials
  Client client = new Client();
  final channel = await client.channel();
  final queue = await channel.queue("test", durable: true);
  final consumer = await queue.consume();
  consumer.listen((message) {
    // Get the payload as a string
    print(" [x] Received string: ${message.payloadAsString}");

    // Or unserialize to json
    print(" [x] Received json: ${message.payloadAsJson}");

    // Or just get the raw data as a Uint8List
    print(" [x] Received raw: ${message.payload}");

    message.ack();
  });
}
```

**Comment by achilleasa** [comment]
The problem seems to be caused by the `message.ack()` statement. The default parameters for queue.consume specify the `noAck: true` flag. Amqp is not expecting an ACK for messages so it sends back an error (you can receive that by adding the onError handler to consumer.listen)

To resolve the problem either remove `message.ack()` or change the `final consumer = await queue.consume();` to `final consumer = await queue.consume(noAck: false);` if you need to ack messages.

**Comment by a14n** [comment]
Thanks! My mistake.

BTW thanks for this package :)
