### ISSUE TITLE
is there a client reconnect config?

### ISSUE THREAD

**Issue by jingjiewei** [achilleasa/dart_amqp#42]
So after the network lost, the the client can connect to mq automatically?

**Comment by achilleasa** [comment]
Currently, automatic reconnect is not supported. However, you can implement this in your application by wrapping your code in a block that catches the raised connection exception, calls the `connect` method on the connection instance and runs your code again. 

Note that as mentioned in the docs, if `connect()` fails to establish a link (e.g. due to transient network issues) it will [wait](https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/connection_settings.dart#L17) and try again.

**Comment by jingjiewei** [comment]
> Currently, automatic reconnect is not supported. However, you can implement this in your application by wrapping your code in a block that catches the raised connection exception, calls the `connect` method on the connection instance and runs your code again.
> 
> Note that as mentioned in the docs, if `connect()` fails to establish a link (e.g. due to transient network issues) it will [wait](https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/connection_settings.dart#L17) and try again.

Thank a lot.
Another question, in my customized "reconnect" method, is it possible to reuse the existing connection/channel/exchange/consumer?  Since if it's a network issue, the old connection actually still exist. (Although in the plugin code, it will try to close the connection when the exception happens, but since network down, it will not take effect).

Really appreciate your help!

**Comment by achilleasa** [comment]
Please take a look at my response [here](https://github.com/achilleasa/dart_amqp/issues/43#issuecomment-650286820). I think you will need to acquire a new channel and redefine your topology and any subscribers each time you reconnect.

**Comment by jingjiewei** [comment]
thanks, really helpful
