### ISSUE TITLE
Publishing on default exchange?

### ISSUE THREAD

**Issue by mmaschenk** [achilleasa/dart_amqp#86]
Hi. I tried to use your library to put a message on the default exchange (which by convention has the empty string as a name) of my server. However, your code does not allow for this (line 547 of client/impl/channel_impl.dart deliberately throws an exception).

Is there a reason the library does not allow this, and is there any other way to publish on the default exchange?

Thanks.

**Comment by achilleasa** [comment]
That is intentional. 

As per the _exchange_ section of the [spec](https://www.rabbitmq.com/amqp-0-9-1-reference.html):

```
- The server MUST NOT allow clients to access the default exchange except by specifying an empty exchange name in the Queue.Bind and content Publish methods. 
```

Even if you allow the request to proceed (e.g. change the check to `if (name.isEmpty && type != ExchangeType.DIRECT){` , rabbitmq would most likely reject the request with an error similar to `ACCESS_REFUSED - operation not permitted on the default exchange`.

You can find more information about how the default direct exchange works [here](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default)
