### ISSUE TITLE
yield inside listen / on.data()

### ISSUE THREAD

**Issue by inselberg** [achilleasa/dart_amqp#88]
How can i yield a message inside the listen or data part (which both are void)?

Par example:
```
 Consumer consumer = await queue.consume(consumerTag: queueName);
 consumer.listen((data) {
      yield data.payloadAsString;
 });
```

```
 Consumer consumer = await queue.consume(consumerTag: queueName);
 var c = consumer.listen((AmqpMessage msg) {});
 c.onData((data) {
     yield data.payloadAsString;
 })
```

**Comment by achilleasa** [comment]
As consumer is a stream I believe you can change the code in your example to use `await for` instead of `.listen` ([example](https://stackoverflow.com/questions/55939917/dart-flutter-yield-inside-a-callback-function)).

As this is more of a general question rather than an issue/bug with the library, I will mark this issue as closed.
